"""initial schema

Revision ID: f85d01c3b7b8
Revises: 
Create Date: 2026-06-15 00:04:27.564053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85d01c3b7b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('target_entity_type', sa.String(), nullable=True),
    sa.Column('target_entity_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('audio_storage_backend', sa.String(), nullable=False),
    sa.Column('audio_relative_path', sa.String(), nullable=False),
    sa.Column('lyrics_text', sa.Text(), nullable=True),
    sa.Column('lyrics_storage_backend', sa.String(), nullable=True),
    sa.Column('lyrics_relative_path', sa.String(), nullable=True),
    sa.Column('visual_bible_text', sa.Text(), nullable=True),
    sa.Column('visual_bible_storage_backend', sa.String(), nullable=True),
    sa.Column('visual_bible_relative_path', sa.String(), nullable=True),
    sa.Column('default_comfyui_server', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('json_path', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('compatibility_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('storage_backend', sa.String(), nullable=False),
    sa.Column('relative_path', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_modes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_template_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('required_inputs', sa.Text(), nullable=False),
    sa.Column('optional_inputs', sa.Text(), nullable=False),
    sa.Column('node_bindings', sa.Text(), nullable=False),
    sa.Column('validation_rules', sa.Text(), nullable=False),
    sa.Column('exposed_params', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_template_id'], ['workflow_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('speaker', sa.String(), nullable=True),
    sa.Column('lyrics_text', sa.Text(), nullable=True),
    sa.Column('shot_note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('active_attempt_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['active_attempt_id'], ['attempts.id'], name='fk_shot_active_attempt', use_alter=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shot_id', sa.String(length=36), nullable=False),
    sa.Column('parent_attempt_id', sa.String(length=36), nullable=True),
    sa.Column('image_storage_backend', sa.String(), nullable=True),
    sa.Column('image_relative_path', sa.String(), nullable=True),
    sa.Column('end_image_storage_backend', sa.String(), nullable=True),
    sa.Column('end_image_relative_path', sa.String(), nullable=True),
    sa.Column('input_video_storage_backend', sa.String(), nullable=True),
    sa.Column('input_video_relative_path', sa.String(), nullable=True),
    sa.Column('shot_note_snapshot', sa.Text(), nullable=True),
    sa.Column('prompt_ko', sa.Text(), nullable=True),
    sa.Column('prompt_en', sa.Text(), nullable=True),
    sa.Column('workflow_template_id', sa.String(length=36), nullable=True),
    sa.Column('execution_mode_id', sa.String(length=36), nullable=True),
    sa.Column('param_overrides', sa.Text(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('workflow_snapshot', sa.Text(), nullable=True),
    sa.Column('comfyui_prompt_id', sa.String(), nullable=True),
    sa.Column('output_metadata', sa.Text(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_mode_id'], ['execution_modes.id'], ),
    sa.ForeignKeyConstraint(['parent_attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ),
    sa.ForeignKeyConstraint(['workflow_template_id'], ['workflow_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attempts')
    op.drop_table('shots')
    op.drop_table('execution_modes')
    op.drop_table('assets')
    op.drop_table('workflow_templates')
    op.drop_table('projects')
    op.drop_table('jobs')
    # ### end Alembic commands ###
