"""integration schema fixes

Revision ID: 21294ea57d30
Revises: eaad71043a60
Create Date: 2026-06-15 10:44:47.564817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21294ea57d30'
down_revision: Union[str, Sequence[str], None] = 'eaad71043a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_modes', schema=None) as batch_op:
        batch_op.alter_column('required_inputs',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('optional_inputs',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('node_bindings',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('validation_rules',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('exposed_params',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_modes', schema=None) as batch_op:
        batch_op.alter_column('exposed_params',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('validation_rules',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('node_bindings',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('optional_inputs',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('required_inputs',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
