"""make audio fields nullable

Revision ID: eaad71043a60
Revises: f85d01c3b7b8
Create Date: 2026-06-15 00:52:57.647030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaad71043a60'
down_revision: Union[str, Sequence[str], None] = 'f85d01c3b7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('audio_storage_backend',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('audio_relative_path',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('audio_relative_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('audio_storage_backend',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
